auth_enabled: false
server:
  http_listen_port: 3100
  log_level: info
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_target_size: 1048576
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
storage_config:
  boltdb:
    directory: /loki/index
  filesystem:
    directory: /loki/chunks
limits_config:
  enforce_metric_name: false
